t = read.table('PreRec_3_folds', sep =';')
roc = read.table('Roc_curve', sep =';')
dev = pdf('./PreRecROC.pdf')
par(mar = par()$mar + c(0,1,0,0))
plot(t, xlim = c(0,1), ylim = c(0,1), type = 'n', main = 'Precision-Recall and ROC curve', ylab = '(a) precision\n(b) recall', xlab = '(a) recall\n(b) false positive rate', cex.lab = 1.2, cex.axis = 1.2, cex.main = 1.5)
legend('right', c('(a) F-Max', '(a) precision-recall', '(b) ROC'), pch = c(1,-1,-1), lty = c(-1,1,2), cex = 1.2)
lines(t)
lines(roc, lty = 2)
points(t[65,1], t[65,2])
dev.off()
