t = read.table('PreRec_3_folds', sep =';')
roc = read.table('ROC_curve', sep =';')
dev = pdf('../report/figures/PreRecROC.pdf')
par(mar = par()$mar + c(0,1,0,0))
plot(t, xlim = c(0,1), ylim = c(0,1), type = 'n', main = 'Precision-Recall and ROC curve', ylab = 'precision/\nrecall', xlab = 'recall/\nfalse positive rate', cex = 1.5)
legend('right', c('F-Max', 'precision-recall', 'ROC'), pch = c(1,-1,-1), lty = c(-1,2,1))
lines(t)
lines(roc, lty = 2)
points(t[65,1], t[65,2])
dev.off()
